export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY'
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM'
